### ISSUE TITLE
Flag -mno-unaligned-access breaks building process on PC

### ISSUE THREAD

**Issue by MarkoSagadin** [edgeimpulse/example-standalone-inferencing#6]
Like the title says,  I tried building the example for my local machine, but flag -mno-unaligned-access is not found as it only applies to ARM processors. Removing it solves the problem and build finishes. Flag can be found in `Makefile.tflite` file.

**Comment by janjongboom** [comment]
Good catch @MarkoSagadin - Clang ignores unknown flags which is why we didn't see it, but this was added on error (interestingly our internal integration tests don't have this flag either). Have pushed a fix.
