### ISSUE TITLE
Error: ‘struct ei_impulse_result_t’ has no member named ‘classification’

### ISSUE THREAD

**Issue by kaisark** [edgeimpulse/example-standalone-inferencing#8]
I followed the steps at [running-your-impulse-locally](https://docs.edgeimpulse.com/docs/running-your-impulse-locally). 

I ran into a compile error when trying to run the example on Ubuntu 20 desktop:

sh build.sh

source/main.cpp: In function ‘int main(int, char**)’:
source/main.cpp:72:31: error: ‘struct ei_impulse_result_t’ has no member named ‘classification’
   72 |         printf("%.5f", result.classification[ix].value);
      |                               ^~~~~~~~~~~~~~
source/main.cpp: In function ‘std::string read_file(const char*)’:
source/main.cpp:28:10: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
   28 |     fread(&ss[0], 1, size, f);
      |     ~~~~~^~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:72: source/main.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by janjongboom** [comment]
@kaisark For object detection models use https://github.com/edgeimpulse/example-standalone-inferencing-linux - we should unify these repos!

**Comment by janjongboom** [comment]
Now also updated this repo.
